---
spring:
  profiles: cs1
server:
  port: 8080

---
server:
  port: 8081
spring:
  profiles: cs2

---
server:
  port: 8082
spring:
  profiles: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
