management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

---
spring:
  profiles: cs1
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration, org.springframework.boot.actuate.autoconfigure.amqp.RabbitHealthContributorAutoConfiguration, org.springframework.boot.actuate.autoconfigure.metrics.amqp.RabbitMetricsAutoConfiguration
server:
  port: 8080

---
server:
  port: 8081
spring:
  profiles: cs2
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration, org.springframework.boot.actuate.autoconfigure.amqp.RabbitHealthContributorAutoConfiguration, org.springframework.boot.actuate.autoconfigure.metrics.amqp.RabbitMetricsAutoConfiguration

---
server:
  port: 8082
spring:
  profiles: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
