---
spring:
  profiles: as1
server:
  port: 8091

---
server:
  port: 8092
spring:
  profiles: as2

---
server:
  port: 8093
spring:
  profiles: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
